import {
  ArrowDownAZ,
  ArrowDownNarrowWide,
  Box,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  Copy,
  Download,
  Eye,
  EyeOff,
  FolderOpen,
  FolderSearch,
  Globe,
  Info,
  LayoutGrid,
  Loader2,
  Monitor,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Trash2,
  Upload,
  Workflow,
} from '@lucide/vue'
import type { Component } from 'vue'

export const iconMap: Record<string, Component> = {
  'pi pi-spinner pi-spin': Loader2,
  'pi pi-info-circle': Info,
  'pi pi-search': Search,
  'pi pi-check-circle': CheckCircle,
  'pi pi-box': Box,
  'pi pi-refresh': RefreshCw,
  'pi pi-folder-open': FolderOpen,
  'pi pi-globe': Globe,
  'pi pi-sort-alpha-down': ArrowDownAZ,
  'pi pi-sort-amount-down': ArrowDownNarrowWide,
  'pi pi-desktop': Monitor,
  'pi pi-pencil': Pencil,
  'pi pi-trash': Trash2,
  'pi pi-th-large': LayoutGrid,
  'pi pi-eye': Eye,
  'pi pi-eye-slash': EyeOff,
  'pi pi-download': Download,
  'pi pi-upload': Upload,
  'pi pi-plus': Plus,
  'pi pi-copy': Copy,
  'pi pi-file-import': Workflow,
  'pi pi-arrow-left': ChevronLeft,
  'pi pi-arrow-right': ChevronRight,
  'pi pi-folder': FolderOpen,
  'md md-folder-search-outline': FolderSearch,
}

export const resolveIcon = (iconStr: string): Component | undefined => {
  return iconMap[iconStr]
}
